Allow code style check failure on non-stable toolchain

diff --git a/azure-pipelines-template.yml b/azure-pipelines-template.yml
--- a/azure-pipelines-template.yml
+++ b/azure-pipelines-template.yml
@@ -40,7 +40,11 @@ jobs:
 
   # Check code style
   - script: |
-      cargo fmt --all -- --check
+      if [[ "$rust_version" == "stable" ]]; then
+        cargo fmt --all -- --check
+      else
+        cargo fmt --all -- --check || echo -e "\043#vso[task.logissue type=warning;] Code style check failed in Rust $(rust_version) toolchain"
+      fi
     displayName: 'Check Code Style'
 
   # Run unit tests
